Nc news task 6
Northerner988/fe-nc-news pull request #3
Opened 2023-05-31 10:36 UTC by Northerner988

2023-05-31 11:07 UTC, Keb84 requested changes
I'm currently getting errors in the console from your SingleArticle when i slow the network down to see your loading state. Please fix these errors and resubmit a PR 👍

2023-06-01 07:53 UTC, MKD01 approved these changes
Great work so far, I have left a comment for you as well and once you have made the change for that im happy for you to merge this in 👍

2023-06-01 07:53 UTC, MKD01 commented on src/components/CommentList.jsx
> +    </ul>
One thing to think about here is what if an article has no comments? What is displayed to the user in that situation?

2023-06-01 07:57 UTC, Northerner988 commented on src/components/CommentList.jsx
> +    </ul>
Okay thank you! I will add an if statement to account for this situation.

2023-06-01 08:19 UTC, merged